// Code generated by protoc-gen-go. DO NOT EDIT.
// source: info.proto

/*
Package protoBuff is a generated protocol buffer package.

It is generated from these files:
	info.proto

It has these top-level messages:
	LoginInfo
*/
package protoBuff

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginInfo struct {
	AppToken string `protobuf:"bytes,1,opt,name=appToken" json:"appToken,omitempty"`
	UserId   int64  `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
	DeviceId string `protobuf:"bytes,3,opt,name=deviceId" json:"deviceId,omitempty"`
}

func (m *LoginInfo) Reset()                    { *m = LoginInfo{} }
func (m *LoginInfo) String() string            { return proto.CompactTextString(m) }
func (*LoginInfo) ProtoMessage()               {}
func (*LoginInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginInfo) GetAppToken() string {
	if m != nil {
		return m.AppToken
	}
	return ""
}

func (m *LoginInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginInfo) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginInfo)(nil), "protoBuff.LoginInfo")
}

func init() { proto.RegisterFile("info.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcc, 0x4b, 0xcb,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0x53, 0x4e, 0xa5, 0x69, 0x69, 0x4a, 0xd1,
	0x5c, 0x9c, 0x3e, 0xf9, 0xe9, 0x99, 0x79, 0x9e, 0x79, 0x69, 0xf9, 0x42, 0x52, 0x5c, 0x1c, 0x89,
	0x05, 0x05, 0x21, 0xf9, 0xd9, 0xa9, 0x79, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0xbe,
	0x90, 0x18, 0x17, 0x5b, 0x69, 0x71, 0x6a, 0x91, 0x67, 0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x73,
	0x10, 0x94, 0x07, 0xd2, 0x93, 0x92, 0x5a, 0x96, 0x99, 0x9c, 0xea, 0x99, 0x22, 0xc1, 0x0c, 0xd1,
	0x03, 0xe3, 0x27, 0xb1, 0x81, 0xed, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x1b, 0xab,
	0x8b, 0x7c, 0x00, 0x00, 0x00,
}
